function [fitresult, gof] = createFit(xplt, yplt, Y_test)
%CREATEFIT(XPLT,YPLT,Y_TEST)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xplt
%      Y Input : yplt
%      Z Output: Y_test
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Mar-2019 15:24:25


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( xplt, yplt, Y_test );

% Set up fittype and options.
ft = fittype( 'poly55' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'LAR';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, [xData, yData], zData );

h = plot( fitresult);
legend( h, 'untitled fit 1', 'Y_test vs. xplt, yplt', 'Location', 'NorthEast' );
% Label axes
xlabel xplt
ylabel yplt
zlabel Y_test
grid on
view( -39.3, 24.9 );


